# Generated by Django 2.1.1 on 2018-09-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employee'},
        ),
        migrations.AddField(
            model_name='client',
            name='frequency',
            field=models.CharField(choices=[('1', '1x semaine'), ('2', '1x 2 semaines'), ('3', '1x 3 semaines'), ('4', '1x mois')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
