# Generated by Django 2.1.1 on 2018-09-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180927_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='animals',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prospect',
            name='assign_to',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='code_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='days',
            field=models.CharField(blank=True, choices=[('Lun', 'Lun'), ('Mar', 'Mar'), ('Mer', 'Mer'), ('Jeu', 'Jeu'), ('Ven', 'Ven'), ('Sam', 'Sam'), ('Dim', 'Dim')], max_length=5),
        ),
        migrations.AddField(
            model_name='prospect',
            name='estimated_time',
            field=models.CharField(blank=True, choices=[('1 heure et demi', '1 heure et demi'), ('2 heures', '2 heures'), ('2 heures et demi', '2 heures et demi'), ('3 heures', '3 heures'), ('3 heures et demi', '3 heures et demi'), ('4 heures', '4 heures'), ('4 heures et demi', '4 heures et demi'), ('5 heures', '5 heures'), ('5 heures et demi', '5 heures et demi'), ('6 heures', '6 heures'), ('6 heures et demi', '6 heures et demi'), ('7 heures', '7 heures'), ('7 heures et demi', '7 heures et demi'), ('8 heures', '8 heures'), ('8 heures et demi', '8 heures et demi'), ('9 heures', '9 heures'), ('9 heures et demi', '9 heures et demi'), ('10 heures', '10 heures')], max_length=15),
        ),
        migrations.AddField(
            model_name='prospect',
            name='frequency',
            field=models.CharField(blank=True, choices=[('1x semaine', '1x semaine'), ('2x semaine', '2x semaine'), ('1x 2 semaines', '1x 2 semaines'), ('1x 3 semaines', '1x 3 semaines'), ('1x 4 semaines', '1x 4 semaines')], max_length=15),
        ),
        migrations.AddField(
            model_name='prospect',
            name='login_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prospect',
            name='payment',
            field=models.CharField(blank=True, choices=[('Virement Interac', 'Virement Interac'), ('Argent comptant', 'Argent comptant'), ('Dépôt direct', 'Dépôt direct'), ('Chèque', 'Chèque'), ('Carte de crédit', 'Carte de crédit')], max_length=30),
        ),
        migrations.AddField(
            model_name='prospect',
            name='profit_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='replacement',
            field=models.CharField(blank=True, choices=[('Reporté le ménage', 'Reporté le ménage'), ('Envoyé un remplaçant', 'Envoyé un remplaçant')], max_length=30),
        ),
    ]
