# Generated by Django 2.1.1 on 2018-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180927_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(blank=True, choices=[('Nouveau', 'Nouveau'), ('Appel manqué #1', 'Appel manqué #1'), ('Appel manqué #2', 'Appel manqué #2'), ('Soumission RDV', 'Soumission RDV'), ('Soumission envoyée', 'Soumission envoyée'), ('Non intéressé', 'Non intéressé'), ('En attente', 'En attente'), ('Nouveau client', 'Nouveau client')], max_length=15),
        ),
    ]
