# Generated by Django 2.1.1 on 2018-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180917_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='customer_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Occasionnel', 'Occasionnel')], max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='frequency',
            field=models.CharField(choices=[('1x_semaine', '1x semaine'), ('1x_2_semaines', '1x 2 semaines'), ('1x_3_semaines', '1x 3 semaines'), ('1x_mois', '1x mois')], max_length=15),
        ),
    ]
