# Generated by Django 2.1.1 on 2018-09-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180917_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profit_month',
            field=models.IntegerField(blank=True, default=100),
            preserve_default=False,
        ),
    ]
