# Generated by Django 2.1.1 on 2018-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180927_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
