# Generated by Django 2.1.1 on 2018-10-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_prospect_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_key',
            field=models.CharField(blank=True, default=1002, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prospect',
            name='code_key',
            field=models.CharField(blank=True, default=2334, max_length=100),
            preserve_default=False,
        ),
    ]
