# Generated by Django 2.1.1 on 2018-09-20 17:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180916_1725'),
        ('api', '0006_auto_20180919_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_contact', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=20)),
                ('stage', models.CharField(choices=[('missed_call_1', 'Missed call # 1'), ('missed_call_2', 'Missed call # 2'), ('rdv_submission', 'RDV submission'), ('submission_feels', 'Submission Feels'), ('new customer', 'New Customer'), ('no_interested', 'No Interested'), ('waiting', 'Waiting')], max_length=15)),
            ],
            options={
                'verbose_name': 'Prospects',
                'verbose_name_plural': 'Prospects',
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
