# Generated by Django 2.1.1 on 2018-09-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_prospect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='assign_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
        migrations.AlterField(
            model_name='client',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Occasionnel', 'Occasionnel')], max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='frequency',
            field=models.CharField(blank=True, choices=[('1x_semaine', '1x semaine'), ('1x_2_semaines', '1x 2 semaines'), ('1x_3_semaines', '1x 3 semaines'), ('1x_mois', '1x mois')], max_length=15),
        ),
    ]
