# Generated by Django 2.1.1 on 2018-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180921_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('id',), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterField(
            model_name='client',
            name='frequency',
            field=models.CharField(blank=True, choices=[('1x_semaine', '1x semaine'), ('2x_semaine', '2x semaine'), ('1x_2_semaines', '1x 2 semaines'), ('1x_3_semaines', '1x 3 semaines'), ('1x_4_semaines', '1x 4 semaines')], max_length=15),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('new customer', 'Nouveau'), ('missed_call_1', 'Appel manqué #1'), ('missed_call_2', 'Appel manqué #2'), ('rdv_submission', 'Soumission RDV'), ('submission_sent', 'Soumission envoyée'), ('no_interested', 'Non intéressé'), ('waiting', 'En attente'), ('new_customer', 'Nouveau client')], max_length=15),
        ),
    ]
