# Generated by Django 2.1.1 on 2018-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180923_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='frequency',
            field=models.CharField(blank=True, choices=[('1x semaine', '1x semaine'), ('2x semaine', '2x semaine'), ('1x 2_semaines', '1x 2 semaines'), ('1x 3_semaines', '1x 3 semaines'), ('1x 4_semaines', '1x 4 semaines')], max_length=15),
        ),
    ]
